[OpenAPI] OAuth
ZeusWPI/g2-backend pull request #70
Opened 2020-07-30 08:39 UTC by maartenvn

Add OAuth endpoints to the OpenAPI spec.

**This is different than the current spec and should be updated**

Partially implements: #48

2020-07-30 14:03 UTC, Jan-PieterBaert reviewed
It looks good to me, but I'll let the people that actually write code for the backend review this

2020-08-03 10:12 UTC, mcbloch commented
You don't want a callback with the provider also in the url??

2020-08-03 10:17 UTC, maartenvn commented
> You don't want a callback with the provider also in the url??

If you are talking about the `{provider}` part in the url, thats just as a placeholder. I didn't want to write the same spec for different providers.

2020-08-03 10:23 UTC, mcbloch commented
Yeah but in the callback url you left out the provider meaning for ex. github and zeus oauth will both end up at the`/oauth/callback` url. If that's intentional then it's okay but I was wondering if it was.

2020-08-03 10:24 UTC, maartenvn commented
It was like that in the original backend. With a provider is fine as well, whatever you prefer.

2020-08-03 10:34 UTC, mcbloch commented
We'll do it with. That way you can still choose to handle them differently if you want to.

2020-11-07 17:54 UTC, mcbloch requested changes

2020-11-07 17:54 UTC, mcbloch commented on openapi/reference/Default.v1.yaml
> +        This should redirect to the backend /oauth/callback after completion.
```suggestion
        This should redirect to the backend /oauth/{provider}/callback after completion.
```

2020-11-07 17:54 UTC, mcbloch commented on openapi/reference/Default.v1.yaml
> +  /oauth/callback:
```suggestion
  /oauth/{provider}/callback:
```

2020-11-07 17:55 UTC, merged